# Generated by Django 5.2 on 2025-04-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_create_fild_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AddField(
            model_name='course',
            name='situation',
            field=models.BooleanField(default=True, verbose_name='Situação'),
        ),
    ]
